### ISSUE TITLE
Rewrite in C++

### ISSUE THREAD

**Issue by EntireTwix** [STBoyden/market-api-2.0#6]
Rust, while safer, is less cool, please fix

**Comment by STBoyden** [comment]
Hmmm.








































































































No.



:)

**Comment by STBoyden** [comment]
Okay after some reconsideration, I have decided

**Comment by STBoyden** [comment]
That my earlier consideration, while correct, could have been more considerate

**Comment by STBoyden** [comment]
But no, no C++ :)
